classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - git
  - name
# strftime format to get something like this: 17 Jun 21 20:14:55
date: "+%b %d %y %H:%M"
color:
  theme: custom
