#!/bin/bash

# path
export PATH="$HOME/.local/share/aquaproj-aqua/bin:$HOME/.cargo/bin:$PATH:$HOME/bin:$HOME/.local/bin"

# aqua setup
export AQUA_GLOBAL_CONFIG=$HOME/.config/aqua.yaml

# my aliases
alias ls="ls --color"
alias ll="ls -la"

# git aliases
alias gs="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias gc="git commit"
alias ga="git add"
alias gl="git log"
alias gpl="git pull"
alias gps="git push"

# use vim as default editor
export EDITOR=/usr/bin/vim
export VISUAL=$EDITOR

test -f ~/.bashrc_work && source ~/.bashrc_work || true
test -f ~/.bashrc_home && source ~/.bashrc_home || true

if bash --version | head -n 1 | egrep -v '(version 2|version 3)' > /dev/null 2>&1; then
    eval "$(starship init bash)"
fi

